# Generated by Django 4.2.4 on 2023-09-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetId', models.CharField(max_length=100)),
                ('isRecording', models.BooleanField(default=True)),
            ],
        ),
    ]
