# Generated by Django 4.2.4 on 2023-09-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_meet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetIdURl', models.CharField(max_length=100)),
                ('script', models.TextField()),
            ],
        ),
    ]
